import type { TimelineDraft, TimelineOutcome, TimelineType } from "@/lib/server/customer-timeline";

export type DocumentType = "notarization_document" | "identification" | "supporting_document" | "affidavit" | "acknowledgment" | "jurat" | "consent" | "attachment" | "other";
export type DocumentStatus = "draft" | "awaiting_upload" | "uploaded" | "pending_signature" | "signed" | "completed" | "archived";
export type DocumentSource = "admin" | "booking" | "appointment" | "automation" | "system";
export type DocumentRecord = Readonly<{ id: string; organizationId: string; customerId: string; customerName: string; appointmentId: string | null; displayName: string; documentType: DocumentType; status: DocumentStatus; description: string | null; createdAt: string; updatedAt: string; uploadedAt: string | null; completedAt: string | null; archivedAt: string | null; source: DocumentSource; correlationId: string | null; metadata: Readonly<Record<string, string | number | boolean | null>> }>;
export type DocumentQuery = Readonly<{ organizationId: string; status?: string; type?: string; customerId?: string; appointmentId?: string; search?: string; sort?: string; limit?: string }>;

const types: readonly DocumentType[] = ["notarization_document", "identification", "supporting_document", "affidavit", "acknowledgment", "jurat", "consent", "attachment", "other"];
const statuses: readonly DocumentStatus[] = ["draft", "awaiting_upload", "uploaded", "pending_signature", "signed", "completed", "archived"];
const records = new Map<string, DocumentRecord>();

export function documentIdentity(input: Pick<DocumentRecord, "organizationId" | "customerId" | "appointmentId" | "documentType" | "displayName">) { return [input.organizationId, input.customerId, input.appointmentId ?? "", input.documentType, input.displayName].map((value) => `${value.length}:${value}`).join("."); }
export function queryDocuments(input: DocumentQuery) { const search = input.search?.trim().toLowerCase(); return [...records.values()].filter((document) => document.organizationId === input.organizationId && (!types.includes(input.type as DocumentType) || document.documentType === input.type) && (!statuses.includes(input.status as DocumentStatus) || document.status === input.status) && (!input.customerId || document.customerId === input.customerId) && (!input.appointmentId || document.appointmentId === input.appointmentId) && (!search || [document.id, document.displayName, document.customerName, document.appointmentId].filter(Boolean).some((value) => value!.toLowerCase().includes(search)))).sort((a, b) => input.sort === "oldest" ? a.updatedAt.localeCompare(b.updatedAt) : b.updatedAt.localeCompare(a.updatedAt)).slice(0, Math.min(Math.max(Number(input.limit ?? "50") || 50, 1), 100)); }
export function getDocument(organizationId: string, id: string) { const document = records.get(`${organizationId}:${id}`); return document ? { ...document, metadata: { ...document.metadata } } : null; }
export function timelineFromDocument(document: DocumentRecord): TimelineDraft { const type: TimelineType = document.status === "uploaded" ? "document_uploaded" : document.status === "signed" ? "document_signed" : document.status === "completed" ? "document_completed" : document.status === "archived" ? "document_archived" : document.status === "pending_signature" ? "document_reviewed" : "document_requested"; const outcome: TimelineOutcome = document.status === "completed" || document.status === "signed" ? "succeeded" : document.status === "archived" ? "cancelled" : document.status === "uploaded" ? "informational" : "pending"; return { organizationId: document.organizationId, customerId: document.customerId, appointmentId: document.appointmentId, category: "document", type, outcome, title: document.displayName, safeSummary: `Document ${type.replace("document_", "").replaceAll("_", " ")}.`, occurredAt: document.updatedAt, actor: { kind: "system", actorId: null, safeDisplayName: "Documents" }, source: "document_service", correlationId: document.correlationId, causationId: document.id, sourceEventId: document.id, automationExecutionId: null, automationRuleId: null, automationRuleVersion: null, communicationRequestId: null, paymentId: null, documentId: document.id, metadata: {} }; }
