import type { TimelineDraft, TimelineOutcome, TimelineType } from "@/lib/server/customer-timeline";
export type WorkflowStage = "appointment_scheduled" | "awaiting_payment" | "awaiting_documents" | "ready_for_identity_verification" | "ready_for_notarization" | "notarization_complete" | "follow_up" | "closed";
export type WorkflowBlocker = "payment_required" | "documents_required" | "customer_action_required" | "identity_verification_pending" | "notary_action_required" | "communication_failed" | "manual_review_required";
export type Workflow = Readonly<{ id: string; organizationId: string; customerId: string; customerName: string; appointmentId: string; currentStage: WorkflowStage; previousStage: WorkflowStage | null; progressPercent: number; blockers: readonly WorkflowBlocker[]; recommendedNextAction: string; createdAt: string; updatedAt: string; completedAt: string | null; correlationId: string | null }>;
const progress: Record<WorkflowStage, number> = { appointment_scheduled: 10, awaiting_payment: 20, awaiting_documents: 40, ready_for_identity_verification: 60, ready_for_notarization: 80, notarization_complete: 100, follow_up: 100, closed: 100 };
const actions: Record<WorkflowStage, string> = { appointment_scheduled: "Review appointment", awaiting_payment: "Collect payment", awaiting_documents: "Upload documents", ready_for_identity_verification: "Verify identity", ready_for_notarization: "Join notarization session", notarization_complete: "Complete follow-up", follow_up: "Complete follow-up", closed: "No action required" };
const workflows = new Map<string, Workflow>();
export function workflowIdentity(input: Pick<Workflow, "organizationId" | "customerId" | "appointmentId">) { return [input.organizationId, input.customerId, input.appointmentId].map((value) => `${value.length}:${value}`).join("."); }
export function createWorkflow(input: Omit<Workflow, "id" | "progressPercent" | "recommendedNextAction">): Workflow { return { ...input, id: workflowIdentity(input), progressPercent: progress[input.currentStage], recommendedNextAction: actions[input.currentStage], blockers: [...input.blockers] }; }
export function queryWorkflows(input: { organizationId: string; stage?: string; blocker?: string; search?: string; sort?: string }) { const term = input.search?.toLowerCase(); return [...workflows.values()].filter((workflow) => workflow.organizationId === input.organizationId && (!input.stage || workflow.currentStage === input.stage) && (!input.blocker || workflow.blockers.includes(input.blocker as WorkflowBlocker)) && (!term || [workflow.customerName, workflow.appointmentId, workflow.id].some((value) => value.toLowerCase().includes(term)))).sort((a, b) => input.sort === "oldest" ? a.updatedAt.localeCompare(b.updatedAt) : b.updatedAt.localeCompare(a.updatedAt)); }
export function timelineFromWorkflow(workflow: Workflow): TimelineDraft { const type: TimelineType = workflow.currentStage === "closed" ? "workflow_closed" : workflow.completedAt ? "workflow_completed" : workflow.previousStage ? "workflow_stage_changed" : "workflow_started"; const outcome: TimelineOutcome = workflow.blockers.length ? "requires_attention" : workflow.completedAt ? "succeeded" : "informational"; return { organizationId: workflow.organizationId, customerId: workflow.customerId, appointmentId: workflow.appointmentId, category: "appointment", type, outcome, title: "Workflow updated", safeSummary: `Workflow is ${workflow.currentStage.replaceAll("_", " ")}.`, occurredAt: workflow.updatedAt, actor: { kind: "system", actorId: null, safeDisplayName: "Workflow" }, source: "system", correlationId: workflow.correlationId, causationId: workflow.id, sourceEventId: workflow.id, automationExecutionId: null, automationRuleId: null, automationRuleVersion: null, communicationRequestId: null, paymentId: null, documentId: null, metadata: { progressPercent: workflow.progressPercent } }; }
