import { NextResponse } from "next/server";
import { consumeDistributedRateLimit, rateLimitedResponse, requestRateLimitIdentity, type RateLimitPolicy, type RateLimitResult } from "@/lib/server/distributed-rate-limit";
import { repository } from "@/lib/server/repository";
type TokenStatus = NonNullable<Awaited<ReturnType<typeof repository.getCustomerAppointmentByAccessToken>>>;
type PaymentResult = Awaited<ReturnType<typeof repository.createPaymentLink>>;
export type ClientPaymentHandlerDependencies = Readonly<{ requestIdentity: (request: Request) => string; consumeRateLimit: (policy: RateLimitPolicy, identity: string) => Promise<RateLimitResult>; resolveAppointment: (token: string) => Promise<TokenStatus | null>; createPaymentLink: (appointmentId: string) => Promise<PaymentResult> }>;
const productionDependencies: ClientPaymentHandlerDependencies = { requestIdentity: requestRateLimitIdentity, consumeRateLimit: consumeDistributedRateLimit, resolveAppointment: (token) => repository.getCustomerAppointmentByAccessToken(token), createPaymentLink: (appointmentId) => repository.createPaymentLink(appointmentId) };
export function createClientPaymentHandler(dependencies: ClientPaymentHandlerDependencies = productionDependencies) { return async function handlePayment(request: Request, { params }: { params: Promise<{ token: string }> }) { const { token } = await params; let ipRate; try { ipRate = await dependencies.consumeRateLimit("client_payment_ip", dependencies.requestIdentity(request)); } catch { return rateLimitedResponse(60); } if (!ipRate.allowed) return rateLimitedResponse(ipRate.retryAfterSeconds); const status = await dependencies.resolveAppointment(token); if (!status) return unavailable(404); let scopedRate; try { scopedRate = await dependencies.consumeRateLimit("client_payment_scoped", `${status.organizationId}:${status.appointmentId}`); } catch { return rateLimitedResponse(60); } if (!scopedRate.allowed) return rateLimitedResponse(scopedRate.retryAfterSeconds); if (status.paymentStatus === "paid") return NextResponse.json({ status: "already_paid" }, { headers: noStore }); try { const result = await dependencies.createPaymentLink(status.appointmentId); if (!result.payment.checkoutUrl) return unavailable(409); return NextResponse.json({ status: "checkout_ready", checkoutUrl: result.payment.checkoutUrl }, { headers: noStore }); } catch { return unavailable(409); } }; }
const noStore = { "Cache-Control": "no-store" }; function unavailable(status: number) { return NextResponse.json({ status: "unavailable" }, { status, headers: noStore }); }
