"use client";

import React, { useState } from "react";
import { AdminCard } from "@/components/admin-shell";
import { Button } from "@/components/button";

type Module = { id: string; version: string };
type Attempt = { id: string; state: "in_progress" | "stopped"; currentModuleIndex: number; modules: Module[]; stopReason: string | null };
type StopReason = "notarial_act_not_established" | "unsupported_notarial_act" | "unsupported_signing_procedure" | "notary_disqualification" | "notary_not_in_florida" | "identity" | "technology" | "willingness" | "capacity" | "incomplete_document" | "outside_florida_confirmation" | "remote_witness" | "remote_witness_presence" | "declined_consent" | "acknowledgment_language" | "certificate_completion";

export function AdminFloridaRonProductionSession({ appointmentId }: { appointmentId: string }) {
  const [attempt, setAttempt] = useState<Attempt | null>(null); const [stopReasons, setStopReasons] = useState<StopReason[]>([]); const [selectedStopReason, setSelectedStopReason] = useState<"" | StopReason>(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const mutate = async (body: Record<string, unknown>) => { setBusy(true); setMessage(""); const response = await fetch(`/api/admin/appointments/${encodeURIComponent(appointmentId)}/session-assistant/production`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as { attempt?: Attempt; applicableStopReasons?: StopReason[]; error?: string; unresolvedRequirementIds?: string[] }; if (response.ok && result.attempt) { setAttempt(result.attempt); setStopReasons(result.applicableStopReasons ?? []); setSelectedStopReason(""); } else setMessage(result.unresolvedRequirementIds?.join(", ") ?? result.error ?? "Production action is unavailable."); setBusy(false); };
  const current = attempt?.modules[attempt.currentModuleIndex] ?? null;
  return <AdminCard><p className="text-xs font-semibold uppercase tracking-wide text-red-800">Production execution</p><h2 className="mt-1 text-xl font-semibold text-navy">Production Session Assistant</h2><p className="mt-2 text-sm text-slateDeep">This is separate from Candidate Preview. Production completion is not enabled in this implementation stage.</p>{!attempt ? <Button className="mt-4" type="button" disabled={busy} onClick={() => void mutate({ action: "start" })}>Start ceremony</Button> : <div className="mt-4 space-y-3"><p className="text-sm text-slateDeep">{attempt.state === "stopped" ? `Stopped: ${attempt.stopReason ?? "safe STOP"}` : current ? <React.Fragment><code>{current.id}</code> · version <code>{current.version}</code></React.Fragment> : "Production completion is not enabled."}</p>{attempt.state === "in_progress" && current ? <div className="flex flex-wrap gap-3"><Button type="button" disabled={busy} onClick={() => void mutate({ action: "confirm", requirementId: `module_complete:${current.id}@${current.version}` })}>Record notary confirmation</Button><Button type="button" variant="secondary" disabled={busy} onClick={() => void mutate({ action: "advance" })}>Advance module</Button><label className="text-sm font-semibold text-navy">Safe STOP reason<select aria-label="Production STOP reason" value={selectedStopReason} onChange={(event) => setSelectedStopReason(event.target.value as "" | StopReason)} className="ml-2 rounded border border-slate-500 bg-white px-2 py-2"><option value="">Select STOP reason…</option>{stopReasons.map((reason) => <option key={reason} value={reason}>{reason.replaceAll("_", " ")}</option>)}</select></label><Button type="button" variant="secondary" disabled={busy || !selectedStopReason} onClick={() => void mutate({ action: "stop", stopReason: selectedStopReason })}>STOP ceremony</Button></div> : null}</div>}{message ? <p role="alert" className="mt-3 text-sm font-semibold text-red-800">{message}</p> : null}</AdminCard>;
}
