import React from "react";
import Link from "next/link";
import { AdminCard } from "@/components/admin-shell";
import { StatusBadge } from "@/components/status-badge";
import type { AppointmentNextAction } from "@/lib/server/appointment-next-action";
import type { AppointmentStatus } from "@/lib/types";

type Communication = Readonly<{ messageType: string; status: string; sentAt: string | null }>;

export function AdminProviderWorkspace({ customerName, serviceName, scheduledAt, appointmentStatus, paymentStatus, readinessSummary, action, communications, documents, session }: { customerName: string; serviceName: string; scheduledAt: string; appointmentStatus: AppointmentStatus; paymentStatus: string | null; readinessSummary: string; action: AppointmentNextAction; communications: readonly Communication[]; documents: React.ReactNode; session: React.ReactNode }) {
  const sessionCommunication = communications.find((message) => message.messageType === "external_session_available");
  const completion = action.kind === "confirm_appointment_outcome" ? "Provider session marked completed. Confirm the appointment outcome before updating the appointment status." : appointmentStatus === "completed" ? "This appointment is recorded as completed." : "Use Status Management to record the appointment outcome when appropriate.";
  return <section className="space-y-6" aria-labelledby="provider-workspace-heading"><AdminCard><h2 id="provider-workspace-heading" className="text-xl font-semibold text-navy">Provider Workspace</h2><div className="mt-4 grid gap-3 text-sm sm:grid-cols-2"><p><b>Customer:</b> {customerName}</p><p><b>Service:</b> {serviceName}</p><p><b>Scheduled:</b> {scheduledAt}</p><div><b>Appointment:</b> <StatusBadge status={appointmentStatus} /></div><p><b>Payment:</b> {paymentStatus?.replaceAll("_", " ") ?? "Not recorded"}</p><p><b>Readiness:</b> {readinessSummary}</p></div><p className="mt-4 text-sm text-slateDeep"><b>Current next action:</b> {action.title}</p></AdminCard><section id="documents" aria-labelledby="provider-documents-heading"><h3 id="provider-documents-heading" className="sr-only">Documents</h3>{documents}</section><section id="external-session" aria-labelledby="provider-session-heading"><h3 id="provider-session-heading" className="sr-only">Provider Session</h3>{session}</section><AdminCard><h3 className="text-xl font-semibold text-navy">Communications</h3><p className="mt-3 text-sm text-slateDeep">{!sessionCommunication ? "No session communication is recorded yet." : ["queued", "processing"].includes(sessionCommunication.status) ? "Session communication is processing." : sessionCommunication.status === "failed" ? "Session communication failed." : `Session communication ${sessionCommunication.status}.`}</p>{sessionCommunication?.status === "failed" ? <Link className="focus-ring mt-3 inline-block font-semibold text-emeraldAction underline" href="/admin/communications">Open Communications Center</Link> : null}</AdminCard><AdminCard><h3 className="text-xl font-semibold text-navy">Appointment Completion</h3><p className="mt-3 text-sm text-slateDeep">{completion}</p><Link className="focus-ring mt-3 inline-block font-semibold text-emeraldAction underline" href="#status-management">Open Status Management</Link></AdminCard></section>;
}
