import React from "react";
import Link from "next/link";
import { CheckCircle2, CircleAlert, Clock3, Mail, XCircle } from "lucide-react";
import { communicationTypeLabel, CommunicationStatusBadge, formatCommunicationTime } from "@/components/admin-communications";
import type { CommunicationsCenterItem, CommunicationsCenterResult } from "@/lib/server/communications-center";

export function CommunicationsCenter({ result, timezone }: { result: CommunicationsCenterResult; timezone: string }) {
  return <section aria-labelledby="communications-list-heading"><div className="flex flex-wrap items-baseline justify-between gap-3"><div><h2 id="communications-list-heading" className="text-xl font-semibold text-navy">All communications</h2><p className="mt-1 text-sm text-slateDeep">Read-only delivery records for this organization.</p></div><p className="text-sm text-slateDeep">{result.totalRecords} record{result.totalRecords === 1 ? "" : "s"}</p></div><CommunicationsFilters query={result.query} /><CommunicationList records={result.records} timezone={timezone} /></section>;
}

export function CommunicationsFilters({ query }: { query: CommunicationsCenterResult["query"] }) {
  return <form className="mt-5 grid gap-3 rounded-lg border border-silver bg-mist p-4 sm:grid-cols-2 xl:grid-cols-4" aria-label="Filter communications">
    <label className="grid gap-1 text-sm font-medium text-navy">Search<input name="search" defaultValue={query.search} placeholder="Customer, appointment, or ID" className="rounded-md border border-silver bg-white px-3 py-2 text-sm" /></label>
    <label className="grid gap-1 text-sm font-medium text-navy">Status<select name="status" defaultValue={query.status ?? ""} className="rounded-md border border-silver bg-white px-3 py-2 text-sm"><option value="">All statuses</option><option value="scheduled">Scheduled</option><option value="ready_to_queue">Ready to queue</option><option value="queued">Queued</option><option value="sent">Delivered</option><option value="failed">Failed</option><option value="cancelled">Cancelled</option></select></label>
    <label className="grid gap-1 text-sm font-medium text-navy">Purpose<input name="purpose" defaultValue={query.purpose} placeholder="e.g. appointment_reminder_24h" className="rounded-md border border-silver bg-white px-3 py-2 text-sm" /></label>
    <label className="grid gap-1 text-sm font-medium text-navy">Channel<select name="channel" defaultValue={query.channel ?? ""} className="rounded-md border border-silver bg-white px-3 py-2 text-sm"><option value="">All channels</option><option value="email">Email</option></select></label>
    <label className="grid gap-1 text-sm font-medium text-navy">Customer ID<input name="customer" defaultValue={query.customer} className="rounded-md border border-silver bg-white px-3 py-2 text-sm" /></label>
    <label className="grid gap-1 text-sm font-medium text-navy">Appointment ID<input name="appointment" defaultValue={query.appointment} className="rounded-md border border-silver bg-white px-3 py-2 text-sm" /></label>
    <label className="grid gap-1 text-sm font-medium text-navy">From<input name="from" type="date" defaultValue={query.from} className="rounded-md border border-silver bg-white px-3 py-2 text-sm" /></label>
    <label className="grid gap-1 text-sm font-medium text-navy">To<input name="to" type="date" defaultValue={query.to} className="rounded-md border border-silver bg-white px-3 py-2 text-sm" /></label>
    <label className="grid gap-1 text-sm font-medium text-navy">Order<select name="sort" defaultValue={query.sort} className="rounded-md border border-silver bg-white px-3 py-2 text-sm"><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label>
    <div className="flex items-end"><button type="submit" className="focus-ring rounded-md bg-navy px-4 py-2 text-sm font-semibold text-white hover:bg-navy/90">Apply filters</button></div>
  </form>;
}

export function CommunicationList({ records, timezone }: { records: readonly CommunicationsCenterItem[]; timezone: string }) {
  if (!records.length) return <div className="mt-5 rounded-lg border border-silver bg-white p-5 text-sm text-slateDeep">No communications have been sent yet.</div>;
  return <div className="mt-5"><div className="hidden overflow-x-auto rounded-lg border border-silver bg-white md:block"><table className="w-full text-left text-sm"><thead className="text-xs uppercase tracking-wide text-slateDeep"><tr><th className="border-b border-silver p-3">Purpose</th><th className="border-b border-silver p-3">Customer</th><th className="border-b border-silver p-3">Appointment</th><th className="border-b border-silver p-3">Channel</th><th className="border-b border-silver p-3">Status</th><th className="border-b border-silver p-3">Occurred</th><th className="border-b border-silver p-3">Provider</th></tr></thead><tbody>{records.map((record) => <CommunicationRow key={record.id} record={record} timezone={timezone} table />)}</tbody></table></div><div className="space-y-3 md:hidden">{records.map((record) => <CommunicationRow key={record.id} record={record} timezone={timezone} />)}</div></div>;
}

export function CommunicationRow({ record, timezone, table = false }: { record: CommunicationsCenterItem; timezone: string; table?: boolean }) {
  const body = <><div className="flex items-start gap-3"><StatusIcon status={record.status} /><div><CommunicationPurposeBadge purpose={record.purpose} /><Link href={`/admin/communications/${encodeURIComponent(record.id)}`} className="focus-ring mt-2 block rounded-sm font-semibold text-navy underline underline-offset-4">View communication</Link><p className="mt-1 text-xs text-slateDeep">{record.safeSummary}</p><CommunicationRetryAction record={record} /></div></div></>;
  if (table) return <tr className="border-b border-silver/70 align-top"><td className="p-3">{body}</td><td className="p-3">{record.customerId ? <Link href={`/admin/customers/${encodeURIComponent(record.customerId)}`} className="focus-ring text-emeraldAction underline underline-offset-4">{record.customerName ?? "Customer"}</Link> : "Not linked"}</td><td className="p-3">{record.appointmentId ? <Link href={`/admin/appointments/${encodeURIComponent(record.appointmentId)}`} className="focus-ring text-emeraldAction underline underline-offset-4">{record.appointmentId}</Link> : "Not linked"}</td><td className="p-3 text-slateDeep">Email</td><td className="p-3"><CommunicationStatusBadge status={record.status} /></td><td className="p-3 text-slateDeep">{formatCommunicationTime(record.occurredAt, timezone)}</td><td className="p-3 text-slateDeep">Not recorded</td></tr>;
  return <article className="rounded-lg border border-silver bg-white p-4"><div className="flex justify-between gap-3">{body}<CommunicationStatusBadge status={record.status} /></div><dl className="mt-4 grid grid-cols-2 gap-3 text-sm"><Meta label="Customer" value={record.customerId ? <Link href={`/admin/customers/${encodeURIComponent(record.customerId)}`} className="focus-ring text-emeraldAction underline underline-offset-4">{record.customerName ?? "Customer"}</Link> : "Not linked"} /><Meta label="Appointment" value={record.appointmentId ? <Link href={`/admin/appointments/${encodeURIComponent(record.appointmentId)}`} className="focus-ring text-emeraldAction underline underline-offset-4">Open appointment</Link> : "Not linked"} /><Meta label="Channel" value="Email" /><Meta label="Occurred" value={formatCommunicationTime(record.occurredAt, timezone)} /></dl></article>;
}

export function CommunicationPurposeBadge({ purpose }: { purpose: string }) { return <span className="inline-flex rounded-md border border-blue-200 bg-blue-50 px-2.5 py-1 text-xs font-semibold text-blue-900">{communicationTypeLabel(purpose)}</span>; }

export function CommunicationsLoadingState() { return <section role="status" aria-label="Loading Communications Center" className="space-y-6"><div className="space-y-3"><div className="h-9 w-64 animate-pulse rounded-md bg-silver/60 motion-reduce:animate-none" /><div className="h-5 w-full max-w-2xl animate-pulse rounded-md bg-silver/60 motion-reduce:animate-none" /></div><div className="h-56 w-full animate-pulse rounded-md bg-silver/60 motion-reduce:animate-none" /><div className="h-80 w-full animate-pulse rounded-md bg-silver/60 motion-reduce:animate-none" /></section>; }

export function CommunicationsErrorState() { return <section role="alert" className="rounded-lg border border-silver bg-white p-5"><h1 className="text-2xl font-semibold text-navy">Communications are unavailable</h1><p className="mt-3 text-sm leading-6 text-slateDeep">We couldn’t load communications right now. No provider details were exposed.</p></section>; }

export function CommunicationDetail({ record, timezone, timeline }: { record: CommunicationsCenterItem; timezone: string; timeline: React.ReactNode }) {
  return <div className="mt-6 grid gap-6 lg:grid-cols-[minmax(0,1fr)_360px]"><div className="space-y-6"><section className="rounded-lg border border-silver bg-white p-5" aria-labelledby="communication-details-heading"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 id="communication-details-heading" className="text-xl font-semibold text-navy">Communication details</h2><p className="mt-2 text-sm text-slateDeep">Read-only execution record.</p><CommunicationRetryAction record={record} /></div><CommunicationStatusBadge status={record.status} /></div><dl className="mt-5 grid gap-4 text-sm sm:grid-cols-2"><Meta label="Purpose" value={<CommunicationPurposeBadge purpose={record.purpose} />} /><Meta label="Channel" value="Email" /><Meta label="Customer" value={record.customerId ? <Link href={`/admin/customers/${encodeURIComponent(record.customerId)}`} className="focus-ring text-emeraldAction underline underline-offset-4">{record.customerName ?? "Open customer"}</Link> : "Not linked"} /><Meta label="Appointment" value={record.appointmentId ? <Link href={`/admin/appointments/${encodeURIComponent(record.appointmentId)}`} className="focus-ring text-emeraldAction underline underline-offset-4">Open appointment</Link> : "Not linked"} /><Meta label="Provider" value={record.provider ?? "Not recorded"} /><Meta label="Timeline" value={record.customerId ? <Link href={`/admin/customers/${encodeURIComponent(record.customerId)}`} className="focus-ring text-emeraldAction underline underline-offset-4">Open customer timeline</Link> : "Not linked"} /><Meta label="Automation rule" value="Not recorded" /><Meta label="Correlation ID" value="Not recorded" /><Meta label="Request ID" value={record.messageId ?? "Not recorded"} /><Meta label="Execution result" value={record.status === "sent" ? "Delivered" : record.status.replaceAll("_", " ")} /><Meta label="Occurred" value={formatCommunicationTime(record.occurredAt, timezone)} /><Meta label="Safe summary" value={record.safeSummary} /></dl></section><section className="rounded-lg border border-silver bg-white p-5" aria-labelledby="timeline-preview-heading"><h2 id="timeline-preview-heading" className="text-xl font-semibold text-navy">Timeline preview</h2><div className="mt-4">{timeline}</div></section></div><aside className="rounded-lg border border-silver bg-mist p-5"><h2 className="text-xl font-semibold text-navy">Delivery context</h2><p className="mt-3 text-sm leading-6 text-slateDeep">Provider payloads, provider identifiers, and raw delivery errors are intentionally unavailable in this read-only view.</p></aside></div>;
}

function CommunicationRetryAction({ record }: { record: CommunicationsCenterItem }) {
  if (record.status !== "failed" || !record.messageId) return null;
  return <form action={`/api/admin/communications/${encodeURIComponent(record.messageId)}/retry`} method="post" className="mt-3"><button type="submit" className="focus-ring rounded-md border border-navy/55 px-3 py-1.5 text-xs font-semibold text-navy hover:bg-mist">Retry delivery</button></form>;
}

function StatusIcon({ status }: { status: CommunicationsCenterItem["status"] }) { const Icon = status === "sent" ? CheckCircle2 : status === "failed" ? CircleAlert : status === "cancelled" ? XCircle : status === "queued" ? Mail : Clock3; return <Icon className={status === "failed" ? "mt-0.5 text-red-700" : status === "sent" ? "mt-0.5 text-emeraldAction" : "mt-0.5 text-slateDeep"} size={18} aria-label={status === "sent" ? "Delivered" : status} />; }
function Meta({ label, value }: { label: string; value: React.ReactNode }) { return <div><dt className="text-xs font-semibold uppercase tracking-wide text-slateDeep">{label}</dt><dd className="mt-1 break-words text-navy">{value}</dd></div>; }
