import React from "react";
import Link from "next/link";
import { AdminCard } from "@/components/admin-shell";
import { formatPaymentAmount, type PaymentRecord } from "@/lib/server/payments";

const styles: Record<PaymentRecord["status"], string> = { payment_link_created: "border-blue-300 bg-blue-50 text-blue-900", payment_processing: "border-blue-300 bg-blue-50 text-blue-900", paid: "border-emerald-300 bg-emerald-50 text-emerald-900", failed: "border-red-300 bg-red-50 text-red-900", expired: "border-zinc-300 bg-zinc-50 text-zinc-800", refunded: "border-slate-300 bg-slate-50 text-slate-800", partially_refunded: "border-amber-300 bg-amber-50 text-amber-900", disputed: "border-amber-300 bg-amber-50 text-amber-900" };
export function PaymentStatusBadge({ status }: { status: PaymentRecord["status"] }) { return <span className={`inline-flex rounded-md border px-2 py-1 text-xs font-semibold ${styles[status]}`}>{status.replaceAll("_", " ")}</span>; }
export function PaymentsCenter({ records }: { records: readonly PaymentRecord[] }) { return <section aria-labelledby="payments-heading"><div className="flex items-center justify-between gap-3"><div><h1 id="payments-heading" className="text-3xl font-semibold text-navy">Payments Center</h1><p className="mt-2 text-sm text-slateDeep">Read-only appointment payment records.</p></div></div><form className="mt-6 grid gap-3 sm:grid-cols-3" aria-label="Filter payments"><input name="search" placeholder="Customer, appointment, or payment ID" className="rounded-md border border-silver px-3 py-2 text-sm" /><select name="status" className="rounded-md border border-silver px-3 py-2 text-sm"><option value="">All statuses</option>{Object.keys(styles).map((status) => <option key={status}>{status}</option>)}</select><button className="focus-ring rounded-md bg-navy px-4 py-2 text-sm font-semibold text-white">Apply filters</button></form>{records.length === 0 ? <p className="mt-6 rounded-lg border border-silver bg-white p-5 text-sm text-slateDeep">No payment records have been created yet.</p> : <div className="mt-6 space-y-3">{records.map((payment) => <AdminCard key={payment.id} className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><Link href={`/admin/payments/${payment.id}`} className="focus-ring font-semibold text-navy underline underline-offset-4">{formatPaymentAmount(payment.amountMinor, payment.currency)} · {payment.purpose.replaceAll("_", " ")}</Link><p className="mt-1 text-sm text-slateDeep"><Link href={`/admin/customers/${payment.customerId}`} className="focus-ring text-emeraldAction underline underline-offset-4">{payment.customerName}</Link> · <Link href={`/admin/appointments/${payment.appointmentId}`} className="focus-ring text-emeraldAction underline underline-offset-4">Appointment</Link></p></div><PaymentStatusBadge status={payment.status} /></AdminCard>)}</div>}</section>; }
export function PaymentDetail({ payment }: { payment: PaymentRecord }) { const rows = [["Amount", formatPaymentAmount(payment.amountMinor, payment.currency)], ["Purpose", payment.purpose.replaceAll("_", " ")], ["Status", payment.status.replaceAll("_", " ")], ["Description", payment.description], ["Requested", payment.requestedAt], ["Due", payment.dueAt ?? "Not recorded"], ["Paid", payment.paidAt ?? "Not recorded"], ["Refunded", payment.refundedAt ?? "Not recorded"], ["Source", payment.source], ["Safe reference", payment.safeReference ?? "Not recorded"], ["Correlation ID", payment.correlationId ?? "Not recorded"]]; return <AdminCard><h1 className="text-3xl font-semibold text-navy">Payment detail</h1><dl className="mt-6 grid gap-3 text-sm">{rows.map(([label, value]) => <div key={label} className="grid gap-1 border-b border-silver pb-3 sm:grid-cols-[180px_1fr]"><dt className="font-semibold text-slateDeep">{label}</dt><dd className="break-words text-navy">{value}</dd></div>)}</dl></AdminCard>; }
