import React from "react";
import Link from "next/link";
import { AdminCard } from "@/components/admin-shell";
import type { CopilotBrief, CopilotRecommendation } from "@/lib/server/copilot-types";

const priorityStyles = { critical: "bg-red-100 text-red-900", high: "bg-amber-100 text-amber-900", medium: "bg-blue-100 text-blue-900", low: "bg-mist text-slateDeep" } as const;

export function CopilotBriefCard({ brief }: { brief: CopilotBrief }) {
  return <AdminCard><header><p className="text-sm font-semibold text-emeraldAction">Operations Copilot · Read-only</p><h1 className="mt-1 text-3xl font-semibold text-navy">Aven</h1><p className="mt-2 text-sm text-slateDeep">{brief.generatedAt ? `Generated ${formatTime(brief.generatedAt)}` : "Freshness unavailable"}</p></header><section className="mt-6" aria-labelledby="todays-brief-heading"><h2 id="todays-brief-heading" className="text-xl font-semibold text-navy">Today’s brief</h2><p className="mt-3 font-semibold text-navy">{brief.greeting} {brief.headline}</p><dl className="mt-4 grid gap-4 sm:grid-cols-3"><BriefItem label="Schedule" value={brief.scheduleSummary} /><BriefItem label="Attention" value={brief.attentionSummary} /><BriefItem label="Readiness" value={brief.readinessSummary} /></dl></section></AdminCard>;
}

function BriefItem({ label, value }: { label: string; value: string }) { return <div className="rounded-md bg-mist p-4"><dt className="text-xs font-semibold uppercase tracking-wide text-slateDeep">{label}</dt><dd className="mt-2 text-sm leading-6 text-navy">{value}</dd></div>; }

export function CopilotRecommendationList({ recommendations, heading = "Recommendations" }: { recommendations: readonly CopilotRecommendation[]; heading?: string }) {
  return <section className="mt-8" aria-labelledby="aven-recommendations-heading"><h2 id="aven-recommendations-heading" className="text-xl font-semibold text-navy">{heading}</h2>{recommendations.length === 0 ? <AdminCard className="mt-4"><p className="text-sm leading-6 text-slateDeep">No immediate recommendations require attention.</p></AdminCard> : <ol className="mt-4 space-y-4">{recommendations.map((recommendation) => <CopilotRecommendationCard key={recommendation.id} recommendation={recommendation} />)}</ol>}</section>;
}

export function CopilotRecommendationCard({ recommendation }: { recommendation: CopilotRecommendation }) {
  return <li><AdminCard><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-xs font-bold ${priorityStyles[recommendation.priority]}`}>{capitalize(recommendation.priority)} priority</span><span className="rounded-full bg-mist px-2.5 py-1 text-xs font-semibold text-slateDeep">{capitalize(recommendation.category)}</span></div><h3 className="mt-3 text-lg font-semibold text-navy">{recommendation.title}</h3></div><span className="text-xs text-slateDeep">High-confidence recorded evidence</span></div><p className="mt-2 text-sm leading-6 text-slateDeep">{recommendation.summary}</p><p className="mt-3 text-sm leading-6 text-slateDeep"><span className="font-semibold text-navy">Why:</span> {recommendation.reason}</p><p className="mt-3 text-sm leading-6 text-slateDeep"><span className="font-semibold text-navy">Recommended next step:</span> {recommendation.recommendedAction}</p>{recommendation.customerName && <p className="mt-3 text-sm text-slateDeep">Customer: {recommendation.customerName}</p>}<details className="mt-4 border-t border-silver pt-4"><summary className="focus-ring cursor-pointer rounded-sm text-sm font-semibold text-emeraldAction underline underline-offset-4">View {recommendation.evidence.length} evidence item{recommendation.evidence.length === 1 ? "" : "s"}</summary><ul className="mt-3 space-y-2 text-sm leading-6 text-slateDeep">{recommendation.evidence.map((item) => <li key={item.id}><span className="font-semibold text-navy">{item.label}:</span> {item.fact}</li>)}</ul><p className="mt-3 text-xs text-slateDeep">Rule: {recommendation.ruleId} v{recommendation.ruleVersion}</p></details>{recommendation.href && <Link href={recommendation.href} className="focus-ring mt-4 inline-block rounded-sm text-sm font-semibold text-emeraldAction underline underline-offset-4">Open related record</Link>}</AdminCard></li>;
}

export function CopilotAvailabilityNotice({ unavailableSections }: { unavailableSections: readonly string[] }) { if (unavailableSections.length === 0) return null; return <AdminCard className="mt-8"><h2 className="text-lg font-semibold text-navy">Data availability</h2><p className="mt-2 text-sm leading-6 text-slateDeep">Aven generated this brief from the available trusted sources. Some sections are partial or unavailable: {unavailableSections.map(capitalize).join(", ")}.</p></AdminCard>; }

export function MissionControlCopilotCard({ brief, recommendations }: { brief: CopilotBrief; recommendations: readonly CopilotRecommendation[] }) { return <AdminCard className="mt-8"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-sm font-semibold text-emeraldAction">Aven’s brief</p><h2 className="mt-1 text-xl font-semibold text-navy">{brief.headline}</h2></div><Link href="/admin/copilot" className="focus-ring rounded-sm text-sm font-semibold text-emeraldAction underline underline-offset-4">Open Aven</Link></div>{recommendations.length > 0 ? <ul className="mt-4 space-y-2 text-sm leading-6 text-slateDeep">{recommendations.map((item) => <li key={item.id}><span className="font-semibold text-navy">{item.title}:</span> {item.summary}</li>)}</ul> : <p className="mt-4 text-sm leading-6 text-slateDeep">Aven does not yet have enough trusted operational data to produce recommendations.</p>}<p className="mt-4 text-xs text-slateDeep">Generated {formatTime(brief.generatedAt)} · Read-only operational guidance</p></AdminCard>; }

function capitalize(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function formatTime(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? "time unavailable" : new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(date); }
