import { NextRequest, NextResponse } from "next/server";
import { consumeDistributedRateLimit, rateLimitedResponse, requestRateLimitIdentity, type RateLimitPolicy, type RateLimitResult } from "@/lib/server/distributed-rate-limit";
import { isCustomerVisibleExternalSession } from "@/lib/server/external-sessions";
import { repository } from "@/lib/server/repository";
type Appointment = NonNullable<Awaited<ReturnType<typeof repository.getCustomerAppointmentByAccessToken>>>; type Session = NonNullable<Awaited<ReturnType<typeof repository.getExternalSession>>>;
export type ExternalSessionLaunchHandlerDependencies = Readonly<{ requestIdentity: (request: NextRequest) => string; consumeRateLimit: (policy: RateLimitPolicy, identity: string) => Promise<RateLimitResult>; resolveAppointment: (token: string) => Promise<Appointment | null>; getSession: (organizationId: string, appointmentId: string) => Promise<Session | null>; recordOpened: (organizationId: string, appointmentId: string, provider: string) => Promise<unknown> }>;
const productionDependencies: ExternalSessionLaunchHandlerDependencies = { requestIdentity: requestRateLimitIdentity, consumeRateLimit: consumeDistributedRateLimit, resolveAppointment: (token) => repository.getCustomerAppointmentByAccessToken(token), getSession: (organizationId, appointmentId) => repository.getExternalSession(organizationId, appointmentId), recordOpened: (organizationId, appointmentId, provider) => repository.recordExternalSessionOpened(organizationId, appointmentId, provider) };
export function createExternalSessionLaunchHandler(dependencies: ExternalSessionLaunchHandlerDependencies = productionDependencies) { return async function handleLaunch(request: NextRequest, { params }: { params: Promise<{ token: string }> }) { const { token } = await params; let ipRate; try { ipRate = await dependencies.consumeRateLimit("external_session_launch_ip", dependencies.requestIdentity(request)); } catch { return rateLimitedResponse(60); } if (!ipRate.allowed) return rateLimitedResponse(ipRate.retryAfterSeconds); try { const appointment = await dependencies.resolveAppointment(token); if (!appointment) return unavailable(); const session = await dependencies.getSession(appointment.organizationId, appointment.appointmentId); if (!isCustomerVisibleExternalSession({ paymentStatus: appointment.paymentStatus, appointmentStatus: appointment.status, organizationId: appointment.organizationId, appointmentId: appointment.appointmentId, session }) || !session?.launchUrl) return unavailable(); let scopedRate; try { scopedRate = await dependencies.consumeRateLimit("external_session_launch_scoped", `${appointment.organizationId}:${appointment.appointmentId}:${session.provider}`); } catch { return rateLimitedResponse(60); } if (!scopedRate.allowed) return rateLimitedResponse(scopedRate.retryAfterSeconds); await dependencies.recordOpened(appointment.organizationId, appointment.appointmentId, session.provider); const response = NextResponse.redirect(session.launchUrl, 302); response.headers.set("Cache-Control", "no-store"); return response; } catch { return unavailable(); } }; }
function unavailable() { return NextResponse.json({ status: "unavailable" }, { status: 404, headers: { "Cache-Control": "no-store" } }); }
