import React from "react";
import Link from "next/link";
import { AppointmentCountdown } from "@/components/appointment-countdown";
import { Brand } from "@/components/brand";
import type { ClientPortalViewModel, PortalItemState } from "@/lib/server/client-portal";

const stateStyle: Record<PortalItemState, string> = { complete: "bg-emeraldAction/10 text-emerald-900", current: "bg-amber-50 text-amber-900", pending: "bg-mist text-slateDeep", unavailable: "bg-mist text-slateDeep" };

export function ClientPortalHome({ portal }: { portal: ClientPortalViewModel }) {
  return <section className="bg-white px-5 py-8 sm:py-12 lg:px-8"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-start justify-between gap-6 border-b border-silver pb-7"><div><Brand /><p className="mt-8 text-sm font-semibold text-emeraldAction">Secure appointment workspace</p><h1 className="mt-2 text-3xl font-semibold tracking-tight text-navy sm:text-4xl">Welcome, {portal.customerName}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slateDeep">Your appointment details and preparation progress are shown below.</p></div><p className="text-sm text-slateDeep">Reference: <span className="font-semibold text-navy">{portal.appointment.reference}</span></p></header><main className="mt-8 grid gap-6 lg:grid-cols-[minmax(0,1.35fr)_minmax(19rem,0.75fr)]"><div className="space-y-6"><AppointmentCard portal={portal} /><ExternalSessionCard portal={portal} /><WorkflowProgress portal={portal} /><PreparationChecklist portal={portal} /><div className="grid gap-6 sm:grid-cols-2"><DocumentStatusCard portal={portal} /><PaymentStatusCard portal={portal} /></div><CommunicationTimeline portal={portal} /></div><aside className="space-y-6"><NextStepCard portal={portal} /><CountdownCard portal={portal} /></aside></main><p className="mt-8 text-xs leading-5 text-slateDeep">This workspace shows recorded appointment information. It does not determine notarial eligibility or provide legal advice.</p></div></section>;
}

export function AppointmentCard({ portal }: { portal: ClientPortalViewModel }) { return <PortalCard heading="Upcoming appointment"><dl className="grid gap-4 sm:grid-cols-2"><Detail label="Service" value={portal.appointment.serviceName} /><Detail label="Date and time" value={`${portal.appointment.date} at ${portal.appointment.time}`} /><Detail label="Timezone" value={portal.appointment.timezone} /><Detail label="Status" value={portal.appointment.statusLabel} /></dl></PortalCard>; }
export function ExternalSessionCard({ portal }: { portal: ClientPortalViewModel }) { return <PortalCard heading="Join your online notarization">{portal.externalSession.availability === "unavailable" ? <p className="text-sm leading-6 text-slateDeep">Your online notarization session has not been scheduled yet. We will share access details when they are available.</p> : <><p className="text-sm font-semibold text-navy">{portal.externalSession.sessionName}</p><p className="mt-2 text-sm text-slateDeep">Provider: {portal.externalSession.provider} · Status: {portal.externalSession.status?.replaceAll("_", " ")}</p><p className="mt-3 text-sm leading-6 text-slateDeep">Use the launch link when instructed by Avenseal. Please prepare your identification and required documents.</p>{portal.externalSession.launchUrl && <a href={portal.externalSession.launchUrl} target="_blank" rel="noreferrer" className="focus-ring mt-4 inline-block rounded-md bg-navy px-4 py-3 text-sm font-semibold text-white">Open session</a>}</>}</PortalCard>; }
export function WorkflowProgress({ portal }: { portal: ClientPortalViewModel }) { return <PortalCard heading="Workflow progress">{portal.workflow.availability === "unavailable" ? <Unavailable message={portal.workflow.reason!} /> : <p className="text-sm text-slateDeep">{portal.workflow.stage}</p>}</PortalCard>; }
export function PreparationChecklist({ portal }: { portal: ClientPortalViewModel }) { return <PortalCard heading="Preparation checklist"><ul className="space-y-3">{portal.checklist.map((item) => <li key={item.id} className="flex items-start gap-3 rounded-md bg-mist p-3"><span className={`mt-0.5 rounded-full px-2 py-1 text-xs font-bold ${stateStyle[item.state]}`}>{item.state === "complete" ? "Complete" : item.state === "current" ? "Current" : item.state === "pending" ? "Pending" : "Unavailable"}</span><div><p className="text-sm font-semibold text-navy">{item.label}</p><p className="mt-1 text-sm leading-5 text-slateDeep">{item.detail}</p></div></li>)}</ul></PortalCard>; }
export function DocumentStatusCard({ portal }: { portal: ClientPortalViewModel }) { return <PortalCard heading="Documents"><Unavailable message={portal.documents.reason!} /></PortalCard>; }
export function PaymentStatusCard({ portal }: { portal: ClientPortalViewModel }) { return <PortalCard heading="Payment status">{portal.payment.availability === "available" ? <p className="text-sm font-semibold text-navy">{portal.payment.label}</p> : <Unavailable message={portal.payment.reason!} />}</PortalCard>; }
export function CommunicationTimeline({ portal }: { portal: ClientPortalViewModel }) { return <PortalCard heading="Recent communications">{portal.communications.availability === "unavailable" ? <Unavailable message={portal.communications.reason!} /> : <ol aria-label="Recent communications" className="space-y-3">{portal.communications.items.map((item) => <li key={`${item.title}-${item.occurredAt}`} className="text-sm text-slateDeep">{item.title}</li>)}</ol>}</PortalCard>; }
export function NextStepCard({ portal }: { portal: ClientPortalViewModel }) { return <PortalCard heading="Your next step"><p className="text-lg font-semibold text-navy">{portal.nextStep.title}</p><p className="mt-2 text-sm leading-6 text-slateDeep">{portal.nextStep.detail}</p><Link href="/contact" className="focus-ring mt-5 inline-block rounded-md border border-navy px-4 py-3 text-sm font-semibold text-navy">Contact Avenseal</Link></PortalCard>; }
export function CountdownCard({ portal }: { portal: ClientPortalViewModel }) { return <PortalCard heading="Appointment countdown"><p className="text-lg font-semibold text-navy"><AppointmentCountdown date={portal.appointment.date} time={portal.appointment.time} /></p><p className="mt-2 text-sm text-slateDeep">Times are displayed in {portal.appointment.timezone}.</p></PortalCard>; }
function PortalCard({ heading, children }: { heading: string; children: React.ReactNode }) { return <section className="rounded-lg border border-silver bg-white p-5 shadow-sm"><h2 className="text-xl font-semibold text-navy">{heading}</h2><div className="mt-4">{children}</div></section>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-xs font-semibold uppercase tracking-wide text-slateDeep">{label}</dt><dd className="mt-1 text-sm font-semibold text-navy">{value}</dd></div>; }
function Unavailable({ message }: { message: string }) { return <p className="text-sm leading-6 text-slateDeep">{message}</p>; }
