import React from "react";
import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";
import { AdminAppointmentNextActionPanel } from "@/components/admin-appointment-next-action-panel";
describe("AdminAppointmentNextActionPanel", () => {
  it("renders one accessible CTA to the supplied existing section target", () => { render(<AdminAppointmentNextActionPanel action={{ kind: "review_payment", title: "Review payment", description: "Payment is required before the appointment can proceed.", tone: "warning", ctaLabel: "Review payment", targetId: "payment" }} />); expect(screen.getByRole("heading", { name: "Next Action" })).toBeTruthy(); expect(screen.getByRole("heading", { name: "Review payment" })).toBeTruthy(); expect(screen.getByRole("link", { name: "Review payment" }).getAttribute("href")).toBe("#payment"); });
  it("does not invent a CTA when no existing action is available", () => { render(<AdminAppointmentNextActionPanel action={{ kind: "no_action_required", title: "No action required", description: "This appointment has been cancelled.", tone: "neutral" }} />); expect(screen.queryByRole("link")).toBeNull(); });
  it("renders only supplied safe presentation text", () => { render(<AdminAppointmentNextActionPanel action={{ kind: "provider_handoff", title: "Download approved document for provider handoff", description: "A clean document is available for an intentional provider-handoff download.", context: "Downloading a document does not confirm provider upload.", tone: "info", ctaLabel: "Review documents", targetId: "documents" }} />); const content = document.body.textContent ?? ""; expect(content).toContain("does not confirm provider upload"); expect(content).not.toContain("storage_key"); expect(content).not.toContain("https://provider.example"); });
});
