import { describe, expect, it } from "vitest";
import { deriveAppointmentNextAction, type AppointmentNextActionInput } from "@/lib/server/appointment-next-action";
const approvedDocument = { status: "approved", scanStatus: "clean", storageStatus: "active", deletedAt: null } as const;
function input(overrides: Partial<AppointmentNextActionInput> = {}): AppointmentNextActionInput { return { appointmentStatus: "confirmed", paymentStatus: "paid", documents: [approvedDocument], externalSession: { status: "ready", customerVisible: true }, communications: [{ messageType: "external_session_available", status: "sent" }], ...overrides }; }
describe("deriveAppointmentNextAction", () => {
  it("keeps terminal and held appointment states ahead of every lower-priority record", () => { expect(deriveAppointmentNextAction(input({ appointmentStatus: "cancelled", paymentStatus: "disputed", documents: [{ ...approvedDocument, scanStatus: "failed" }], externalSession: { status: "cancelled", customerVisible: false } })).kind).toBe("no_action_required"); expect(deriveAppointmentNextAction(input({ appointmentStatus: "clarification_needed", paymentStatus: null, documents: [] })).kind).toBe("review_appointment"); });
  it("keeps payment blockers ahead of documents and sessions", () => { expect(deriveAppointmentNextAction(input({ paymentStatus: "payment_processing", documents: [{ ...approvedDocument, scanStatus: "failed" }], externalSession: null })).kind).toBe("review_payment"); expect(deriveAppointmentNextAction(input({ paymentStatus: "disputed" })).kind).toBe("review_payment_status"); });
  it("prioritizes document security over document review and provider handoff", () => { expect(deriveAppointmentNextAction(input({ documents: [{ ...approvedDocument, scanStatus: "pending", storageStatus: "quarantined" }] })).kind).toBe("security_processing"); expect(deriveAppointmentNextAction(input({ documents: [{ ...approvedDocument, scanStatus: "infected", storageStatus: "quarantined" }] })).kind).toBe("review_document_security"); expect(deriveAppointmentNextAction(input({ documents: [{ ...approvedDocument, storageStatus: "removed" }] })).kind).toBe("review_document_security"); });
  it("keeps rejected and uploaded review states ahead of provider handoff", () => { expect(deriveAppointmentNextAction(input({ documents: [{ ...approvedDocument, status: "rejected" }] })).kind).toBe("resolve_rejected_document"); expect(deriveAppointmentNextAction(input({ documents: [{ ...approvedDocument, status: "uploaded" }] })).kind).toBe("review_uploaded_document"); });
  it("offers provider handoff only for approved, clean, active documents", () => { const action = deriveAppointmentNextAction(input({ externalSession: null })); expect(action).toMatchObject({ kind: "provider_handoff", targetId: "documents", ctaLabel: "Review documents" }); expect(action.description).not.toMatch(/uploaded to BlueNotary|identity verification|notarization is complete/i); expect(action.context).toMatch(/does not confirm/i); });
  it("prepares the provider session only after payment and document prerequisites", () => { expect(deriveAppointmentNextAction(input({ externalSession: { status: "scheduled", customerVisible: false } })).kind).toBe("prepare_session"); });
  it("requires session communication before ready-for-appointment review", () => { expect(deriveAppointmentNextAction(input({ communications: [] })).kind).toBe("review_session_communication"); expect(deriveAppointmentNextAction(input({ communications: [{ messageType: "external_session_available", status: "queued" }] })).kind).toBe("review_session_communication"); expect(deriveAppointmentNextAction(input()).kind).toBe("ready_for_appointment_review"); });
  it("represents in-progress and completed sessions without inferring a notarial outcome", () => { const inProgress = deriveAppointmentNextAction(input({ externalSession: { status: "in_progress", customerVisible: true } })); expect(inProgress.kind).toBe("session_in_progress"); const completed = deriveAppointmentNextAction(input({ externalSession: { status: "completed", customerVisible: true } })); expect(completed.kind).toBe("confirm_appointment_outcome"); expect(completed.description).not.toMatch(/notarization is complete/i); expect(deriveAppointmentNextAction(input({ externalSession: { status: "cancelled", customerVisible: false } })).kind).toBe("resolve_cancelled_session"); });
  it("fails safely for unexpected values", () => { expect(deriveAppointmentNextAction(input({ appointmentStatus: "future_state" })).kind).toBe("review_appointment"); expect(deriveAppointmentNextAction(input({ documents: [{ ...approvedDocument, scanStatus: "unknown" }] })).kind).toBe("review_appointment"); expect(deriveAppointmentNextAction(input({ externalSession: { status: "unexpected" as "ready", customerVisible: false } })).kind).toBe("review_appointment"); });
});
