import { describe, expect, it, vi } from "vitest";
import { createClientDocumentUploadHandler } from "@/app/api/appointments/access/[token]/documents/handler";
import type { RateLimitPolicy, RateLimitResult } from "@/lib/server/distributed-rate-limit";

const allowed: RateLimitResult = { allowed: true, retryAfterSeconds: 60 };
const appointment = { organizationId: "org-1", appointmentId: "appointment-1" };
const request = () => ({ headers: new Headers({ "x-forwarded-for": "203.0.113.9" }), formData: vi.fn().mockResolvedValue({ getAll: () => [new File(["pdf"], "safe.pdf", { type: "application/pdf" })], get: () => null }) } as unknown as Request);
function handler(overrides: Record<string, unknown> = {}) { const resolveAppointment = vi.fn().mockResolvedValue(appointment); const upload = vi.fn().mockResolvedValue({ id: "document-1", originalFilename: "safe.pdf", uploadedAt: "2026-08-01T00:00:00Z", status: "uploaded" }); const consumeRateLimit = vi.fn<(policy: RateLimitPolicy, identity: string) => Promise<RateLimitResult>>().mockResolvedValue(allowed); return { resolveAppointment, upload, consumeRateLimit, handle: createClientDocumentUploadHandler({ requestIdentity: () => "203.0.113.9", consumeRateLimit, resolveAppointment, upload, ...overrides }) }; }
const params = (token = "secret-token") => ({ params: Promise.resolve({ token }) });
describe("Client Workspace document upload rate limits", () => {
  it("runs the existing upload workflow only after IP and trusted scoped limits", async () => { const target = handler(); const response = await target.handle(request(), params()); expect(response.status).toBe(200); expect(target.resolveAppointment).toHaveBeenCalledWith("secret-token"); expect(target.consumeRateLimit).toHaveBeenCalledWith("client_document_upload_ip", "203.0.113.9"); expect(target.consumeRateLimit).toHaveBeenCalledWith("client_document_upload_scoped", "org-1:appointment-1"); expect(target.upload).toHaveBeenCalledOnce(); });
  it("blocks before token resolution on IP blocks and before upload on scoped blocks or limiter failures", async () => { const ip = handler({ consumeRateLimit: vi.fn().mockResolvedValue({ allowed: false, retryAfterSeconds: 12 }) }); const ipResponse = await ip.handle(request(), params()); expect(ipResponse.status).toBe(429); expect(ipResponse.headers.get("Cache-Control")).toBe("no-store"); expect(await ipResponse.json()).toEqual({ status: "rate_limited" }); expect(ip.resolveAppointment).not.toHaveBeenCalled(); expect(ip.upload).not.toHaveBeenCalled(); const scoped = handler({ consumeRateLimit: vi.fn().mockResolvedValueOnce(allowed).mockResolvedValueOnce({ allowed: false, retryAfterSeconds: 12 }) }); expect((await scoped.handle(request(), params())).status).toBe(429); expect(scoped.resolveAppointment).toHaveBeenCalledOnce(); expect(scoped.upload).not.toHaveBeenCalled(); const failed = handler({ consumeRateLimit: vi.fn().mockRejectedValue(new Error("unavailable")) }); expect((await failed.handle(request(), params())).status).toBe(429); expect(failed.upload).not.toHaveBeenCalled(); });
  it("keeps invalid, revoked, and expired tokens unavailable without upload or token leakage", async () => { const target = handler({ resolveAppointment: vi.fn().mockResolvedValue(null) }); for (const token of ["invalid", "revoked", "expired"]) { const response = await target.handle(request(), params(token)); const body = await response.text(); expect(response.status).toBe(404); expect(body).toBe('{"status":"unavailable"}'); expect(body).not.toContain(token); } expect(target.upload).not.toHaveBeenCalled(); });
});
