import { describe, expect, it, vi } from "vitest";
import { createClientPaymentHandler } from "@/app/api/appointments/access/[token]/payment/handler";
import type { RateLimitPolicy, RateLimitResult } from "@/lib/server/distributed-rate-limit";
const allowed: RateLimitResult = { allowed: true, retryAfterSeconds: 60 }; const payable = { appointmentId: "appointment-a", organizationId: "organization-a", paymentStatus: "payment_link_created" };
const request = () => new Request("http://localhost/api/appointments/access/secret-token/payment", { method: "POST", headers: { "x-forwarded-for": "203.0.113.9" } }); const params = () => ({ params: Promise.resolve({ token: "secret-token" }) });
function handler(overrides: Record<string, unknown> = {}) { const resolveAppointment = vi.fn().mockResolvedValue(payable); const createPaymentLink = vi.fn().mockResolvedValue({ payment: { checkoutUrl: "https://checkout.example/secret" } }); const consumeRateLimit = vi.fn<(policy: RateLimitPolicy, identity: string) => Promise<RateLimitResult>>().mockResolvedValue(allowed); return { resolveAppointment, createPaymentLink, handle: createClientPaymentHandler({ requestIdentity: () => "203.0.113.9", consumeRateLimit, resolveAppointment, createPaymentLink, ...overrides }) }; }
describe("Client Workspace payment rate limits", () => {
 it("runs payment only after IP and trusted scoped limits", async () => { const target = handler(); const response = await target.handle(request(), params()); expect(response.status).toBe(200); expect(target.resolveAppointment).toHaveBeenCalledWith("secret-token"); expect(target.createPaymentLink).toHaveBeenCalledWith("appointment-a"); });
 it("blocks before token lookup on IP blocks and before payment on scoped blocks or limiter failures", async () => { const ip = handler({ consumeRateLimit: vi.fn().mockResolvedValue({ allowed: false, retryAfterSeconds: 12 }) }); expect((await ip.handle(request(), params())).status).toBe(429); expect(ip.resolveAppointment).not.toHaveBeenCalled(); expect(ip.createPaymentLink).not.toHaveBeenCalled(); const scoped = handler({ consumeRateLimit: vi.fn().mockResolvedValueOnce(allowed).mockResolvedValueOnce({ allowed: false, retryAfterSeconds: 12 }) }); expect((await scoped.handle(request(), params())).status).toBe(429); expect(scoped.resolveAppointment).toHaveBeenCalledOnce(); expect(scoped.createPaymentLink).not.toHaveBeenCalled(); const failed = handler({ consumeRateLimit: vi.fn().mockRejectedValue(new Error("unavailable")) }); const failedResponse = await failed.handle(request(), params()); expect(failedResponse.status).toBe(429); expect(await failedResponse.json()).toEqual({ status: "rate_limited" }); expect(failed.createPaymentLink).not.toHaveBeenCalled(); });
 it("preserves paid and invalid-token safe behavior", async () => { const paid = handler({ resolveAppointment: vi.fn().mockResolvedValue({ ...payable, paymentStatus: "paid" }) }); expect(await (await paid.handle(request(), params())).json()).toEqual({ status: "already_paid" }); expect(paid.createPaymentLink).not.toHaveBeenCalled(); const invalid = handler({ resolveAppointment: vi.fn().mockResolvedValue(null) }); const response = await invalid.handle(request(), params()); expect(response.status).toBe(404); expect((await response.text())).not.toContain("secret-token"); });
});
