import { NextRequest } from "next/server";
import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks = vi.hoisted(() => ({ getCustomerAppointmentByAccessToken: vi.fn(), getExternalSession: vi.fn(), recordExternalSessionOpened: vi.fn() }));
vi.mock("@/lib/server/repository", () => ({ repository: mocks }));
import { GET } from "@/app/api/appointments/access/[token]/external-session/launch/route";
const appointment = { appointmentId: "appointment", organizationId: "org", paymentStatus: "paid", status: "confirmed" };
const session = { appointmentId: "appointment", organizationId: "org", provider: "BlueNotary", sessionName: "Session", launchUrl: "https://provider.example/session", referenceNumber: "private", status: "scheduled", notes: "private", createdAt: "now", updatedAt: "now", metadata: {} };
const call = (token = "token") => GET(new NextRequest(`http://localhost/api/appointments/access/${token}/external-session/launch?appointmentId=other&launchUrl=https://evil.example`), { params: Promise.resolve({ token }) });
describe("external-session launch endpoint", () => {
  beforeEach(() => { vi.resetAllMocks(); mocks.getCustomerAppointmentByAccessToken.mockResolvedValue(appointment); mocks.getExternalSession.mockResolvedValue(session); mocks.recordExternalSessionOpened.mockResolvedValue(undefined); });
  it("redirects only to the trusted eligible session and writes safe audit data", async () => { const response = await call(); expect(response.status).toBe(302); expect(response.headers.get("location")).toBe(session.launchUrl); expect(response.headers.get("Cache-Control")).toBe("no-store"); expect(mocks.getExternalSession).toHaveBeenCalledWith("org", "appointment"); expect(mocks.recordExternalSessionOpened).toHaveBeenCalledWith("org", "appointment", "BlueNotary"); });
  it.each([null, { ...appointment, paymentStatus: "payment_link_created" }, { ...appointment, status: "cancelled" }])("returns a safe unavailable response when trusted eligibility fails", async (value) => { mocks.getCustomerAppointmentByAccessToken.mockResolvedValue(value); const response = await call("invalid"); expect(response.status).toBe(404); expect(response.headers.get("Cache-Control")).toBe("no-store"); await expect(response.json()).resolves.toEqual({ status: "unavailable" }); expect(mocks.recordExternalSessionOpened).not.toHaveBeenCalled(); });
  it.each([{ ...session, organizationId: "other" }, { ...session, appointmentId: "other" }, { ...session, launchUrl: "http://unsafe.example" }, { ...session, status: "completed" }])("does not expose mismatched or unsafe sessions", async (value) => { mocks.getExternalSession.mockResolvedValue(value); const response = await call(); expect(response.status).toBe(404); await expect(response.json()).resolves.toEqual({ status: "unavailable" }); });
});
