import { describe, expect, it, vi } from "vitest";
import { NextRequest } from "next/server";
import { floridaRonModules11, prepareSession11Schema } from "@/lib/server/florida-ron-session-assistant";

const mocks = vi.hoisted(() => ({ context: vi.fn(), appointment: vi.fn(), prepared: vi.fn(), get: vi.fn(), create: vi.fn(), evidence: vi.fn(), add: vi.fn(), transition: vi.fn() }));
vi.mock("@/lib/server/admin-context", () => ({ requireAdminOrganizationContext: mocks.context }));
vi.mock("@/lib/server/repository", () => ({ repository: { getAppointment: mocks.appointment, getFloridaRonPreparedAttempt: mocks.prepared, getFloridaRonProductionAttempt: mocks.get, createFloridaRonProductionAttempt: mocks.create, getFloridaRonProductionEvidence: mocks.evidence, addFloridaRonProductionEvidence: mocks.add, transitionFloridaRonProductionAttempt: mocks.transition } }));
import { POST } from "@/app/api/admin/appointments/[id]/session-assistant/production/route";

const parameters = prepareSession11Schema.parse({ jurisdiction: "Florida", notarialAct: "jurat", supportedSigningProcedure: true, notaryConfirmedNoApplicableDisqualification: true, notaryState: "Florida", notaryCounty: "Orange", principals: [{ fullName: "Principal", location: "florida", identityMethod: "personally_known", identityStatus: "passed", capacity: "individual", documentDescription: "Record", outsideFloridaConfirmation: null, notaryConfirmedDocumentComplete: true, englishLanguageUnderstanding: "yes", notaryConfirmedRequiredTranslationProvided: null }], witnesses: [], special117285: false, physicalWitnessCount: 0, notaryConfirmedProviderScreeningCompleted: null, notaryConfirmedRequiredWrittenNoticeProvided: null, section117285ScreeningResult: "not_applicable" });
const prepared = { sessionId: "candidate-1", specificationStatus: "candidate", workflowVersion: "FL-RON-1.1", parameters, modules: [floridaRonModules11.core, floridaRonModules11.identity], stopReason: null };
const production = { id: "production-1", organizationId: "org-1", appointmentId: "appointment-1", preparedSessionId: "candidate-1", workflowVersion: "FL-RON-1.1", preparedParameters: parameters, modules: prepared.modules, state: "in_progress", currentModuleIndex: 0, stopReason: null, createdBy: "admin-1", createdAt: "now", startedAt: "now", terminalAt: null };
function request(body: unknown) { return new NextRequest("http://localhost/api/admin/appointments/appointment-1/session-assistant/production", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); }
function setup() { vi.clearAllMocks(); mocks.context.mockResolvedValue({ userId: "admin-1", organizationId: "org-1", role: "owner" }); mocks.appointment.mockResolvedValue({ id: "appointment-1", organizationId: "org-1" }); mocks.prepared.mockResolvedValue(prepared); mocks.get.mockResolvedValue(production); mocks.evidence.mockResolvedValue([]); mocks.create.mockResolvedValue(production); mocks.add.mockImplementation(async (_org: string, item: unknown) => item); mocks.transition.mockResolvedValue(production); }

describe("Production Session Assistant route", () => {
  it("creates an independent immutable production snapshot from the prepared Candidate route", async () => { setup(); mocks.get.mockResolvedValueOnce(null); const response = await POST(request({ action: "start" }), { params: Promise.resolve({ id: "appointment-1" }) }); expect(response.status).toBe(201); expect(mocks.create).toHaveBeenCalledWith(expect.objectContaining({ preparedSessionId: "candidate-1", workflowVersion: "FL-RON-1.1", modules: prepared.modules, currentModuleIndex: 0, state: "in_progress" })); expect(prepared).toMatchObject({ specificationStatus: "candidate", sessionId: "candidate-1" }); });
  it("rejects cross-tenant appointments and blocked candidates before any mutation", async () => { setup(); mocks.appointment.mockResolvedValue({ id: "appointment-1", organizationId: "org-2" }); expect((await POST(request({ action: "start" }), { params: Promise.resolve({ id: "appointment-1" }) })).status).toBe(404); expect(mocks.create).not.toHaveBeenCalled(); setup(); mocks.prepared.mockResolvedValue({ ...prepared, stopReason: "identity" }); expect((await POST(request({ action: "start" }), { params: Promise.resolve({ id: "appointment-1" }) })).status).toBe(409); });
  it("uses only the persisted current module and server-owned NOTARY_CONFIRMED provenance", async () => { setup(); const response = await POST(request({ action: "confirm", requirementId: "module_complete:FL-CORE@1.0", source: "SYSTEM_OBSERVED", moduleId: "FL-IDENTITY" }), { params: Promise.resolve({ id: "appointment-1" }) }); expect(response.status).toBe(201); expect(await response.json()).toMatchObject({ attempt: { id: "production-1", currentModuleIndex: 0 }, evidence: { attemptId: "production-1", moduleId: "FL-CORE", source: "NOTARY_CONFIRMED" } }); expect(mocks.add).toHaveBeenCalledWith("org-1", expect.objectContaining({ attemptId: "production-1", moduleId: "FL-CORE", source: "NOTARY_CONFIRMED" })); expect((await POST(request({ action: "confirm", requirementId: "module_complete:FL-IDENTITY@1.1" }), { params: Promise.resolve({ id: "appointment-1" }) })).status).toBe(409); });
  it("blocks missing evidence, advances exactly one module, rejects invalid STOPs, and never completes", async () => { setup(); let response = await POST(request({ action: "advance", currentModuleIndex: 9 }), { params: Promise.resolve({ id: "appointment-1" }) }); expect(response.status).toBe(409); expect((await response.json()).unresolvedRequirementIds).toEqual(["module_complete:FL-CORE@1.0"]); mocks.evidence.mockResolvedValue([{ id: "e", attemptId: "production-1", moduleId: "FL-CORE", moduleVersion: "1.0", requirementId: "module_complete:FL-CORE@1.0", principalIndex: null, value: true, source: "NOTARY_CONFIRMED", actorId: "admin-1", createdAt: "now" }]); response = await POST(request({ action: "advance" }), { params: Promise.resolve({ id: "appointment-1" }) }); expect(response.status).toBe(200); expect(mocks.transition).toHaveBeenCalledWith(expect.objectContaining({ currentModuleIndex: 1, state: "in_progress", eventType: "module_advanced" })); expect((await POST(request({ action: "stop", stopReason: "identity" }), { params: Promise.resolve({ id: "appointment-1" }) })).status).toBe(409); expect((await POST(request({ action: "stop", stopReason: "not-a-stop" }), { params: Promise.resolve({ id: "appointment-1" }) })).status).toBe(400); });
});
